### ISSUE TITLE
Radio buttons are not visible after loaded by ajax

### ISSUE THREAD

**Issue by faizplus** [timcreative/get-shit-done#2]
After the form is loaded by ajax, the radio buttons are not visible but they can be clicked. And only after a click they become visible. See the image below for a better understanding.

![screencapture-localhost-bv-beat-the-clock-the-hunger-games-trivia-copy-1428441106253](https://cloud.githubusercontent.com/assets/10779658/7033712/c69ffbae-dd99-11e4-8c32-e953cd077d6c.png)

Here the four options radio buttons are invisible. Please let me know if there is any function that can be triggered after loading them. Thanks!

**Comment by faizplus** [comment]
I have just found a solution but that is not what i am looking for. I just appended the default radio template given in gsdk-radio.js <code><span class="icons"><span class="first-icon fa fa-circle-o"></span><span class="second-icon fa fa-dot-circle-o"></span></span></code> 
And its working but is there any other way i can achieve this without appending the long piece of code before each radio button?

**Comment by alexandru-paduraru** [comment]
Hi, 

Just run this 

$('[data-toggle="radio"]').each(function () {
      var $radio = $(this);
      $radio.radio();
    });

after you load the form with ajax. Make sure the inputs have this attribute data-toggle="radio".

Let us know if that is working.

All the best,
Alex

**Comment by faizplus** [comment]
:+1: Thanks Alex it is now working as expected. Thanks once again
